import { CitySchema, LocalServiceSchema, type City, type LocalService } from "./schema";

/**
 * Tier 0 — 12 metros, 4 services (48 city pages + hubs).
 * Held here deliberately (see docs/SEO-ARCHITECTURE.md): a fresh domain
 * launching thousands of near-identical pages is the scaled-content-abuse
 * profile. Expansion is gated on Tier-0 indexing signal.
 *
 * Population/business figures are public-source estimates; CPC bands are
 * estimated ranges for local-service verticals. Pages disclose this.
 */

const CITIES_RAW = [
  { slug: "miami", name: "Miami", stateSlug: "florida", stateName: "Florida", stateAbbr: "FL",
    districts: ["Brickell", "Wynwood", "Coral Gables", "Doral", "Little Havana"],
    character: "A trade-and-tourism economy layered over a fast-growing finance and startup corridor — Brickell towers, Doral logistics parks and neighborhood service businesses all buying very differently.",
    metroPopulation: 6_100_000, businessCount: 730_000,
    industries: ["hospitality", "construction", "healthcare", "real estate", "logistics"],
    cpcBand: [6, 28] as [number, number], competition: "saturated" as const, timezone: "America/New_York",
    nearby: ["fort-lauderdale", "west-palm-beach", "orlando"],
    localNote: "Miami's service market is bilingual by default — ad copy, intake flows and follow-up sequences that only run in English leave measurable volume on the table, and seasonal demand swings around hurricane season are sharp enough to need budget pacing rules of their own." },
  { slug: "fort-lauderdale", name: "Fort Lauderdale", stateSlug: "florida", stateName: "Florida", stateAbbr: "FL",
    districts: ["Las Olas", "Flagler Village", "Port Everglades corridor", "Cypress Creek"],
    character: "A marine-and-professional-services economy where the boatyards of Port Everglades sit twenty minutes from the Cypress Creek office parks.",
    metroPopulation: 1_950_000, businessCount: 240_000,
    industries: ["marine services", "construction", "hospitality", "healthcare"],
    cpcBand: [5, 22] as [number, number], competition: "high" as const, timezone: "America/New_York",
    nearby: ["miami", "west-palm-beach"],
    localNote: "Broward's marine-services cluster is unusual: yacht maintenance, dock construction and marina trades carry ticket sizes closer to commercial than residential work, which changes what a lead is worth and how hard follow-up should push." },
  { slug: "west-palm-beach", name: "West Palm Beach", stateSlug: "florida", stateName: "Florida", stateAbbr: "FL",
    districts: ["Clematis Street", "Rosemary Square", "Northwood", "Palm Beach Lakes corridor"],
    character: "Finance firms relocating onto Flagler share the market with the contractors serving the island's estates — two clienteles, two price books.",
    metroPopulation: 1_530_000, businessCount: 210_000,
    industries: ["construction", "healthcare", "financial services", "hospitality"],
    cpcBand: [5, 24] as [number, number], competition: "high" as const, timezone: "America/New_York",
    nearby: ["fort-lauderdale", "miami"],
    localNote: "Palm Beach County splits into two markets wearing one zip prefix — coastal high-ticket residential and inland volume work — and campaigns that don't separate them pay coastal CPCs for inland jobs." },
  { slug: "orlando", name: "Orlando", stateSlug: "florida", stateName: "Florida", stateAbbr: "FL",
    districts: ["Lake Nona", "Downtown Orlando", "Dr. Phillips", "UCF research corridor"],
    character: "Tourism dollars fund the headlines, but Lake Nona's medical city and the UCF research corridor drive the B2B services demand.",
    metroPopulation: 2_800_000, businessCount: 310_000,
    industries: ["tourism", "construction", "healthcare", "technology"],
    cpcBand: [4, 19] as [number, number], competition: "high" as const, timezone: "America/New_York",
    nearby: ["tampa", "miami"],
    localNote: "Orlando's tourism economy means a large share of searches come from visitors, not buyers — negative-keyword discipline and geo-fencing do more for wasted spend here than bid strategy does." },
  { slug: "tampa", name: "Tampa", stateSlug: "florida", stateName: "Florida", stateAbbr: "FL",
    districts: ["Westshore", "Ybor City", "Water Street", "New Tampa"],
    character: "Westshore is Florida's largest office submarket — a dense B2B services market wrapped inside a fast-growing consumer metro.",
    metroPopulation: 3_300_000, businessCount: 350_000,
    industries: ["healthcare", "construction", "financial services", "logistics"],
    cpcBand: [4, 18] as [number, number], competition: "high" as const, timezone: "America/New_York",
    nearby: ["orlando", "miami"],
    localNote: "Tampa Bay's growth corridors (Wesley Chapel, Riverview, Lakewood Ranch) shift year to year — service-area pages and ad geo targets that were right in 2023 quietly bleed budget into areas the crews no longer prioritize." },
  { slug: "atlanta", name: "Atlanta", stateSlug: "georgia", stateName: "Georgia", stateAbbr: "GA",
    districts: ["Buckhead", "Midtown", "Ponce City Market corridor", "Alpharetta", "The Battery"],
    character: "The Southeast's B2B capital: Buckhead and Midtown towers, an Alpharetta tech corridor, and a logistics ring that moves half the region's freight.",
    metroPopulation: 6_300_000, businessCount: 680_000,
    industries: ["logistics", "film & media", "fintech", "construction", "healthcare"],
    cpcBand: [5, 21] as [number, number], competition: "saturated" as const, timezone: "America/New_York",
    nearby: ["charlotte", "nashville"],
    localNote: "Metro Atlanta's sprawl makes drive-time the hidden qualifier: a lead 40 miles across the perimeter can cost more to serve than it returns, so lead scoring that weighs distance beats raw volume every time here." },
  { slug: "charlotte", name: "Charlotte", stateSlug: "north-carolina", stateName: "North Carolina", stateAbbr: "NC",
    districts: ["Uptown", "South End", "Ballantyne", "University City"],
    character: "A banking town whose South End and Ballantyne growth has spawned a second economy of contractors, agencies and professional services chasing the new rooftops.",
    metroPopulation: 2_800_000, businessCount: 290_000,
    industries: ["banking", "construction", "healthcare", "manufacturing"],
    cpcBand: [4, 17] as [number, number], competition: "moderate" as const, timezone: "America/New_York",
    nearby: ["atlanta", "nashville"],
    localNote: "Charlotte adds roughly a hundred residents a day, and the new-construction warranty cycle that follows creates a predictable second wave of service demand two to three years behind each subdivision — a calendar most local campaigns ignore." },
  { slug: "nashville", name: "Nashville", stateSlug: "tennessee", stateName: "Tennessee", stateAbbr: "TN",
    districts: ["The Gulch", "Music Row", "Wedgewood-Houston", "Cool Springs"],
    character: "Healthcare administration headquarters anchor the economy; Cool Springs and The Gulch carry the professional-services growth that follows it.",
    metroPopulation: 2_100_000, businessCount: 230_000,
    industries: ["healthcare", "music & entertainment", "construction", "hospitality"],
    cpcBand: [4, 18] as [number, number], competition: "moderate" as const, timezone: "America/Chicago",
    nearby: ["atlanta", "charlotte"],
    localNote: "Nashville is a healthcare-administration capital — a B2B sales floor here sells into hospital systems with long committee cycles, which changes what 'speed to lead' means: the first response still wins, but nurture depth decides the deal." },
  { slug: "houston", name: "Houston", stateSlug: "texas", stateName: "Texas", stateAbbr: "TX",
    districts: ["The Galleria", "Energy Corridor", "Texas Medical Center", "The Heights", "Downtown"],
    character: "Energy Corridor procurement culture and the world's largest medical complex make this a market where RFQ discipline decides who wins the work.",
    metroPopulation: 7_300_000, businessCount: 750_000,
    industries: ["energy", "logistics", "healthcare", "construction", "manufacturing"],
    cpcBand: [5, 23] as [number, number], competition: "saturated" as const, timezone: "America/Chicago",
    nearby: ["dallas", "austin"],
    localNote: "Houston's energy-sector procurement culture bleeds into everything: even residential-adjacent trades see RFQ-style multi-bid behavior, so quote follow-up cadence — not ad spend — is usually the highest-leverage fix in this metro." },
  { slug: "dallas", name: "Dallas", stateSlug: "texas", stateName: "Texas", stateAbbr: "TX",
    districts: ["Uptown", "Legacy West", "Deep Ellum", "Las Colinas", "Frisco"],
    character: "Corporate relocations keep filling Legacy West and Las Colinas — a B2B market that grows a new submarket faster than most metros grow a subdivision.",
    metroPopulation: 7_900_000, businessCount: 800_000,
    industries: ["technology", "logistics", "financial services", "construction", "healthcare"],
    cpcBand: [5, 22] as [number, number], competition: "saturated" as const, timezone: "America/Chicago",
    nearby: ["houston", "austin"],
    localNote: "DFW is two ad markets pretending to be one — Dallas-side and Fort Worth-side searches price differently and convert differently, and single-campaign structures average away the difference instead of arbitraging it." },
  { slug: "austin", name: "Austin", stateSlug: "texas", stateName: "Texas", stateAbbr: "TX",
    districts: ["The Domain", "South Congress", "East Austin", "Mueller"],
    character: "A software-native buyer base from The Domain to East Austin that expects product-grade responsiveness from every vendor, trades included.",
    metroPopulation: 2_500_000, businessCount: 270_000,
    industries: ["technology", "construction", "hospitality", "professional services"],
    cpcBand: [5, 20] as [number, number], competition: "high" as const, timezone: "America/Chicago",
    nearby: ["houston", "dallas"],
    localNote: "Austin's buyer expects software-grade responsiveness from everyone — a plumber included. Review velocity and response-time badges move conversion here more than they do in any comparable Texas metro." },
  { slug: "phoenix", name: "Phoenix", stateSlug: "arizona", stateName: "Arizona", stateAbbr: "AZ",
    districts: ["Camelback Corridor", "Old Town Scottsdale", "Tempe", "Deer Valley"],
    character: "Semiconductor money is rebuilding Deer Valley while the Camelback Corridor stays the professional-services spine — a two-speed market in one valley.",
    metroPopulation: 5_100_000, businessCount: 480_000,
    industries: ["construction", "healthcare", "semiconductors", "real estate"],
    cpcBand: [4, 20] as [number, number], competition: "high" as const, timezone: "America/Phoenix",
    nearby: ["austin", "dallas"],
    localNote: "Phoenix demand is seasonal in reverse — HVAC and exterior trades peak in punishing summer while winter brings the snowbird wave and a second population. Budget pacing tuned to a normal seasonal curve is exactly backwards here, and the no-DST timezone quietly breaks scheduled sequences built elsewhere." },
  { slug: "new-york-city", name: "New York City", stateSlug: "new-york", stateName: "New York", stateAbbr: "NY",
    districts: ["Midtown", "SoHo", "DUMBO", "Long Island City", "Financial District"],
    character: "The deepest B2B market in the country, where a vendor is compared against the best money can hire before the first call is ever returned.",
    metroPopulation: 19_500_000, businessCount: 2_200_000,
    industries: ["financial services", "media", "real estate", "healthcare", "professional services"],
    cpcBand: [8, 40] as [number, number], competition: "saturated" as const, timezone: "America/New_York",
    nearby: ["philadelphia", "boston"],
    localNote: "New York punishes slow responders more than any market in America — a Midtown decision-maker fields a dozen vendor pitches a week, and the one that answers in a minute is the one that exists. CPCs here make wasted clicks a rounding error nowhere else can afford." },
  { slug: "los-angeles", name: "Los Angeles", stateSlug: "california", stateName: "California", stateAbbr: "CA",
    districts: ["Santa Monica", "Culver City", "DTLA", "Burbank", "El Segundo"],
    character: "A sprawl of industry clusters — entertainment in Burbank, aerospace in El Segundo, startups in Santa Monica — each behaving like its own city with its own buying culture.",
    metroPopulation: 12_900_000, businessCount: 1_500_000,
    industries: ["entertainment", "logistics", "aerospace", "healthcare", "e-commerce"],
    cpcBand: [7, 32] as [number, number], competition: "saturated" as const, timezone: "America/Los_Angeles",
    nearby: ["san-diego", "las-vegas", "phoenix"],
    localNote: "LA is not one market — a campaign tuned for Santa Monica tech burns money in the San Gabriel Valley, and drive-time across the basin quietly disqualifies leads that look perfect on paper. Geo-segmentation does more here than any bid strategy." },
  { slug: "san-diego", name: "San Diego", stateSlug: "california", stateName: "California", stateAbbr: "CA",
    districts: ["Sorrento Valley", "Gaslamp Quarter", "UTC", "La Jolla"],
    character: "Biotech and defense money anchors a professional-services economy that behaves more conservatively than its beach-town reputation suggests.",
    metroPopulation: 3_300_000, businessCount: 380_000,
    industries: ["biotech", "defense", "tourism", "healthcare"],
    cpcBand: [5, 24] as [number, number], competition: "high" as const, timezone: "America/Los_Angeles",
    nearby: ["los-angeles", "phoenix"],
    localNote: "San Diego's biotech and defense buyers move on procurement calendars, not impulse — the win here is being the vendor whose follow-up is still standing when the budget cycle finally opens, usually months after the first inquiry." },
  { slug: "chicago", name: "Chicago", stateSlug: "illinois", stateName: "Illinois", stateAbbr: "IL",
    districts: ["The Loop", "Fulton Market", "River North", "Schaumburg"],
    character: "The Midwest's commercial capital — old-line industry headquarters downtown and a suburban ring of manufacturers and distributors that buy on relationships and proof.",
    metroPopulation: 9_400_000, businessCount: 950_000,
    industries: ["manufacturing", "logistics", "financial services", "food processing", "healthcare"],
    cpcBand: [5, 24] as [number, number], competition: "saturated" as const, timezone: "America/Chicago",
    nearby: ["minneapolis", "nashville"],
    localNote: "Chicago's suburban manufacturing ring buys nothing without references, which makes the CRM the revenue engine here — the distributor in Schaumburg who bought in 2023 is the warm intro to three more, if anyone remembers to ask." },
  { slug: "philadelphia", name: "Philadelphia", stateSlug: "pennsylvania", stateName: "Pennsylvania", stateAbbr: "PA",
    districts: ["Center City", "University City", "Navy Yard", "King of Prussia"],
    character: "Eds-and-meds money radiating from University City, with King of Prussia carrying one of the largest suburban office markets on the East Coast.",
    metroPopulation: 6_200_000, businessCount: 640_000,
    industries: ["healthcare", "education", "pharmaceuticals", "financial services"],
    cpcBand: [5, 22] as [number, number], competition: "high" as const, timezone: "America/New_York",
    nearby: ["new-york-city", "boston"],
    localNote: "Philadelphia sits close enough to New York that its buyers get the same vendor pitches at two-thirds the CPC — an arbitrage most national campaigns never notice because they treat the corridor as one market." },
  { slug: "boston", name: "Boston", stateSlug: "massachusetts", stateName: "Massachusetts", stateAbbr: "MA",
    districts: ["Seaport", "Kendall Square", "Back Bay", "Route 128"],
    character: "The densest concentration of research money in the country — Kendall Square biotech, Route 128 enterprise software, and the institutional buyers that orbit both.",
    metroPopulation: 4_900_000, businessCount: 560_000,
    industries: ["biotech", "software", "education", "financial services"],
    cpcBand: [6, 28] as [number, number], competition: "saturated" as const, timezone: "America/New_York",
    nearby: ["new-york-city", "philadelphia"],
    localNote: "Boston buyers read before they call — whitepapers, comparisons, the fine print — so the content and SEO side of the funnel does disproportionate work here, and a thin website loses deals a great sales team never hears about." },
  { slug: "seattle", name: "Seattle", stateSlug: "washington", stateName: "Washington", stateAbbr: "WA",
    districts: ["South Lake Union", "Capitol Hill", "Bellevue", "Fremont"],
    character: "Two tech giants' gravity has trained an entire metro of buyers to expect software-grade vendor experiences — self-serve information, instant response, no phone tag.",
    metroPopulation: 4_000_000, businessCount: 480_000,
    industries: ["technology", "aerospace", "maritime", "healthcare"],
    cpcBand: [6, 26] as [number, number], competition: "high" as const, timezone: "America/Los_Angeles",
    nearby: ["denver", "los-angeles"],
    localNote: "Seattle may be the only market where a service business loses a deal for making a customer place a phone call — self-serve booking and instant text-back are table stakes trained into buyers by two decades of working at the two big tech employers." },
  { slug: "denver", name: "Denver", stateSlug: "colorado", stateName: "Colorado", stateAbbr: "CO",
    districts: ["LoDo", "RiNo", "Denver Tech Center", "Cherry Creek"],
    character: "A relocation boomtown where transplanted coastal companies and homegrown outdoor-industry brands share a market that doubles every decade.",
    metroPopulation: 3_000_000, businessCount: 380_000,
    industries: ["technology", "aerospace", "outdoor industry", "construction", "energy"],
    cpcBand: [5, 22] as [number, number], competition: "high" as const, timezone: "America/Denver",
    nearby: ["phoenix", "las-vegas", "seattle"],
    localNote: "Denver's transplant wave means a huge share of buyers arrived without local vendor relationships — the market rewards whoever shows up first in search and responds fastest, because nobody here inherited a guy." },
  { slug: "las-vegas", name: "Las Vegas", stateSlug: "nevada", stateName: "Nevada", stateAbbr: "NV",
    districts: ["The Strip", "Summerlin", "Henderson", "Downtown"],
    character: "Hospitality's capital city, where the convention calendar moves demand for every B2B service in town and residential growth keeps Henderson and Summerlin building.",
    metroPopulation: 2_300_000, businessCount: 250_000,
    industries: ["hospitality", "construction", "events", "logistics"],
    cpcBand: [4, 20] as [number, number], competition: "moderate" as const, timezone: "America/Los_Angeles",
    nearby: ["phoenix", "los-angeles", "denver"],
    localNote: "Vegas demand swings with the convention calendar — the same service gets triple the searches during a major show week — so budget pacing tied to the events schedule outperforms any set-and-forget monthly cap." },
  { slug: "san-antonio", name: "San Antonio", stateSlug: "texas", stateName: "Texas", stateAbbr: "TX",
    districts: ["The Pearl", "Stone Oak", "Medical Center", "Downtown"],
    character: "Military money, one of the country's largest medical centers, and a fast-growing northern corridor give this market steadier demand than its quieter reputation suggests.",
    metroPopulation: 2_600_000, businessCount: 240_000,
    industries: ["military", "healthcare", "manufacturing", "tourism"],
    cpcBand: [3, 16] as [number, number], competition: "moderate" as const, timezone: "America/Chicago",
    nearby: ["austin", "houston", "dallas"],
    localNote: "San Antonio's military rotations mean a constant stream of households and businesses arriving on orders with no local vendor loyalties — and CPCs a fraction of Austin's an hour up the road, for buyers just as real." },
  { slug: "jacksonville", name: "Jacksonville", stateSlug: "florida", stateName: "Florida", stateAbbr: "FL",
    districts: ["San Marco", "Riverside", "Southside", "The Beaches"],
    character: "Logistics and financial back-office headquarters anchor the largest city by land area in the lower 48 — a market where service territory is measured in highway exits.",
    metroPopulation: 1_700_000, businessCount: 190_000,
    industries: ["logistics", "financial services", "construction", "healthcare"],
    cpcBand: [3, 15] as [number, number], competition: "moderate" as const, timezone: "America/New_York",
    nearby: ["orlando", "tampa"],
    localNote: "Jacksonville covers more ground than any city in the lower 48, so a lead's address matters as much as its intent — routing and drive-time scoring decide margins here before a crew ever rolls." },
  { slug: "minneapolis", name: "Minneapolis", stateSlug: "minnesota", stateName: "Minnesota", stateAbbr: "MN",
    districts: ["North Loop", "Uptown", "Bloomington", "Lowertown St. Paul"],
    character: "More Fortune 500 headquarters per capita than almost anywhere — a market of professional corporate buyers wrapped in Midwestern politeness that reads as indecision but isn't.",
    metroPopulation: 3_700_000, businessCount: 420_000,
    industries: ["retail HQ", "medical devices", "food & agriculture", "financial services"],
    cpcBand: [4, 20] as [number, number], competition: "high" as const, timezone: "America/Chicago",
    nearby: ["chicago", "denver"],
    localNote: "Minnesota-nice means buyers rarely say no — they just go quiet — so pipelines here fill with polite maybes that a disciplined follow-up cadence converts and everyone else miscounts as dead." },
];

const SERVICES_RAW = [
  { slug: "ppc", name: "Agentic PPC", catalogPillar: "marketing" as const, catalogSlug: "paid-media", botName: "Ads Bot",
    headlinePattern: "Agentic PPC Company in {city}, {st}",
    hook: "Reviewed daily, not quarterly.",
    intro: "An ad account managed by an agent reads every search term, every day, and moves budget while the human agencies are preparing next month's slide deck. Same platforms, radically shorter feedback loop.",
    implementationWeeks: 2,
    baseline: [
      { metric: "Search-term review cadence", value: "daily" },
      { metric: "Creative variants in rotation", value: "continuous" },
      { metric: "Budget-shift latency", value: "<24h" },
    ] },
  { slug: "seo", name: "Agentic SEO", catalogPillar: "marketing" as const, catalogSlug: "seo", botName: "SEO Bot",
    headlinePattern: "Agentic SEO Company in {city}, {st}",
    hook: "Maintenance, not a one-time audit.",
    intro: "Rankings decay because nobody re-crawls, re-writes and re-links after the audit PDF lands. An agent runs the crawl on a schedule, fixes what broke, and closes coverage gaps while they are still cheap.",
    implementationWeeks: 3,
    baseline: [
      { metric: "Technical crawl cadence", value: "weekly" },
      { metric: "Rank tracking", value: "daily" },
      { metric: "Content gap refresh", value: "monthly" },
    ] },
  { slug: "crm", name: "Agentic CRM", catalogPillar: "sales" as const, catalogSlug: "crm", botName: "CRM Bot",
    headlinePattern: "Agentic CRM Automation Company in {city}, {st}",
    hook: "Records that update themselves.",
    intro: "A CRM nobody updates is a reporting liability you pay monthly for. An agent logs every call, email and meeting against the right record, advances stages on evidence, and merges the duplicates nobody has time for.",
    implementationWeeks: 2,
    baseline: [
      { metric: "Activity logging", value: "automatic" },
      { metric: "Duplicate hygiene", value: "daily" },
      { metric: "Stalled-deal alerts", value: "real-time" },
    ] },
  { slug: "speed-to-lead", name: "Speed-to-Lead", catalogPillar: "sales" as const, catalogSlug: "inbound", botName: "Speed-to-Lead Bot",
    headlinePattern: "AI Speed-to-Lead Company in {city}, {st}",
    hook: "Under a minute, any hour.",
    intro: "The first responder wins the job, and the decay is measured in minutes. An agent answers every call, form and chat within seconds, qualifies in real conversation, and books straight onto the calendar.",
    implementationWeeks: 2,
    baseline: [
      { metric: "First response", value: "<60s" },
      { metric: "Coverage", value: "24/7" },
      { metric: "Escalation to humans", value: "rule-based" },
    ] },
];

/* Parse at module load — a bad row fails the build, not the SERP. */
export const CITIES: City[] = CITIES_RAW.map((c) => CitySchema.parse(c));
export const LOCAL_SERVICES: LocalService[] = SERVICES_RAW.map((s) => LocalServiceSchema.parse(s));

export const STATES = [...new Map(CITIES.map((c) => [c.stateSlug, { slug: c.stateSlug, name: c.stateName, abbr: c.stateAbbr }])).values()];

export const getService = (slug: string) => LOCAL_SERVICES.find((s) => s.slug === slug);
export const getState = (slug: string) => STATES.find((s) => s.slug === slug);
export const getCity = (stateSlug: string, citySlug: string) =>
  CITIES.find((c) => c.stateSlug === stateSlug && c.slug === citySlug);
export const citiesInState = (stateSlug: string) => CITIES.filter((c) => c.stateSlug === stateSlug);
/**
 * Nearby markets, Lot Sealers-style: hand-picked `nearby` first, then the
 * rest of the same state, then adjacent markets — deduped, capped.
 */
export function nearbyCities(city: City, limit = 5): City[] {
  const out: City[] = [];
  const push = (c?: City) => {
    if (c && c.slug !== city.slug && !out.some((x) => x.slug === c.slug) && out.length < limit) out.push(c);
  };
  city.nearby.forEach((slug) => push(CITIES.find((c) => c.slug === slug)));
  CITIES.filter((c) => c.stateSlug === city.stateSlug).forEach(push);
  CITIES.forEach(push);
  return out;
}

export const fmt = new Intl.NumberFormat("en-US");
